[theme]

# Primary accent for interactive elements
primaryColor = "#8DEBC4"
# primaryColor = "#000000"


# Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = "#D5F5FF"
secondaryBackgroundColor = "#000000"



# backgroundColor = '#fafafa'
backgroundColor = '#17231e'

textColor = "#fafafa"
# '#FFFFFF'

